# Generated by Django 4.1 on 2022-08-06 04:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dob', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishes',
            name='audio',
            field=models.FileField(default=django.utils.timezone.now, upload_to='static/dob/'),
            preserve_default=False,
        ),
    ]
