# Generated by Django 4.1 on 2022-08-06 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dob', '0002_wishes_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishes',
            name='audio',
            field=models.FileField(upload_to='music/'),
        ),
    ]
